#!/bin/bash

if [[ $(pwd) == "$HOME/cppcp" ]]; then
    name=$(cat .stor/source.txt)
    if [[ ! -f .exec/${name}.out ]]; then
		clang++ -g -fno-omit-frame-pointer -include-pch libraries/bits/stdc++.h "${name}.cpp" -std=c++20 -Wno-vla -o ".exec/${name}.out"
    fi
	lldb -o "settings set target.input-path .stor/inp0.txt" ".exec/${name}.out"
fi
