#!/bin/bash

if [[ $(pwd) == "$HOME/cppcp" ]]; then
    name=$(cat .stor/source.txt)
    if [[ ! -f .exec/${name}.out ]]; then
		clang++ -g -fsanitize=address,undefined -fno-omit-frame-pointer -include-pch libraries/bits/stdc++.h "${name}.cpp" -std=c++17 -o ".exec/${name}.out"
    fi
	lldb ".exec/${name}.out"
fi
