#!/bin/bash

if [[ $(pwd) == "$HOME/cppcp" ]]; then
    if [[ $1 = "-n" ]] || [[ $1 = "-t" ]]; then
        name=$(echo $2 | cut -d'.' -f1)
    else
        name=$(echo $1 | cut -d'.' -f1)
    fi

    if [[ ! -f ${name}.cpp ]]; then
        cp .template.cpp "${name}.cpp"
    fi
    nvim "${name}.cpp"
    clang++ -g -fsanitize=address,undefined -fno-omit-frame-pointer -include-pch libraries/bits/stdc++.h "${name}.cpp" -std=c++17 -o ".exec/${name}.out"

    chmod +x .exec/${name}.out
    if [[ $1 = "-t" ]]; then
        tst ${name}
    else
        if [[ $1 != "-n" ]]; then
            .exec/${name}.out
        fi
    fi
    
fi

