#!/bin/bash

if [[ $(pwd) == "$HOME/cppcp" ]]; then
	if [ $1 = "-n" ]; then
		name=$(echo $2 | cut -d'.' -f1)
	else
		name=$(echo $1 | cut -d'.' -f1)
	fi

    if [ ! -f ${name}.cpp ]; then
        cp .template.cpp "${name}.cpp"
    fi
	nvim "${name}.cpp"
	g++ "${name}.cpp" -g -o ".exec/${name}.out"

    chmod +x .exec/${name}.out
	if [[ $1 != "-n" ]]; then
		.exec/${name}.out
	fi
    
fi
