#!/bin/bash

if [[ $(pwd) == "$HOME/cppcp" ]]; then
	if [ $1 = "-n" ]; then
		name=$(echo $2 | cut -d'.' -f1)
	else
		name=$(echo $1 | cut -d'.' -f1)
	fi
	
	if [[ "${name:0:1}" == "t" ]]; then
		judgeid=$(cat .judgeid.txt)
		myid=360410
		if [[ $1 != "-n" ]]; then
			curl -s -X POST "https://timus.online/submit.aspx" \
				--cookie-jar .cookies.txt \
				-F "Action=submit" \
				-F "SpaceID=1" \
				-F "JudgeID=${judgeid}" \
				-F "Language=68" \
				-F "ProblemNum=${name:1}" \
				-F "SourceFile=@${name}.cpp" > /dev/null
			echo "Fetching results"
			sleep 4
		fi
		curl -s "https://timus.online/status.aspx?space=1&num=${name:1}&author=${myid}" | html2text
	else
		cf submit ${name} -f ${name}.cpp
	fi

fi
